const actions = {
  CHANGE_NEWTASK: 'CHANGE_NEWTASK',
  ADD_TASK: 'ADD_TASK',
  REHYDRATE_TASKS: 'REHYDRATE_TASKS',
  CHANGE_LOADING: 'CHANGE_LOADING',
  UPDATE_TASK: 'UPDATE_TASK',
  SET_DIALOG: 'SET_DIALOG',
  SET_CURRENT_TASK: 'SET_CURRENT_TASK',
  REMOVE_TODO: 'REMOVE_TODO',
  CHANGE_CURRENTTASK: 'CHANGE_CURRENTTASK',
  CHANGE_INTERNET_STATUS: 'CHANGE_INTERNET_STATUS',
  UPDATE_TASK_OFFLINE: 'UPDATE_TASK_OFFLINE',
  ENQUEUE_TASK: 'ENQUEUE_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  SYNC_DIALOG_STATE: 'SYNC_DIALOG_STATE',
};

export default actions;
